#define IDH_CSHelp_WSA                                              20000
#define IDH_CSHelp_WSAHowTO                                         21000
#define IDH_CSHelp_WSAHowToEquipment                                21010
#define IDH_CSHelp_WSAHowToSongCreate                               21020
#define IDH_CSHelp_WSAHowToSongCategorize                           21030
#define IDH_CSHelp_WSAHowToSongSort                                 21040
#define IDH_CSHelp_WSAHowToSongIndex                                21050
#define IDH_CSHelp_WSAHowToSlideDisplay                             21060
#define IDH_CSHelp_WSAHowToManualPresentationDisplay                21070
#define IDH_CSHelp_WSAHowToTimedPresentationDisplay                 21080
#define IDH_CSHelp_WSACommandBar                                    22000
#define IDH_CSHelp_WSACommandBarNavigator                           22100
#define IDH_CSHelp_WSACommandBarNavigatorSlideShow                  22110
#define IDH_CSHelp_WSACommandBarNavigatorSlideShowLoad              22111
#define IDH_CSHelp_WSACommandBarNavigatorSlideShowHide              22112
#define IDH_CSHelp_WSACommandBarNavigatorSlideShowRun               22113
#define IDH_CSHelp_WSACommandBarNavigatorSlideShowPause             22114
#define IDH_CSHelp_WSACommandBarNavigatorSlideShowNextEffect        22115
#define IDH_CSHelp_WSACommandBarNavigatorSlideShowPrevEffect        22116
#define IDH_CSHelp_WSACommandBarNavigatorGeneral                    22120
#define IDH_CSHelp_WSACommandBarNavigatorGeneralExit                22121
#define IDH_CSHelp_WSACommandBarNavigatorGeneralHelp                22122
#define IDH_CSHelp_WSACommandBarNavigatorPresentationSelection      22130
#define IDH_CSHelp_WSACommandBarNavigatorPresentationSelectionTitle 22131
#define IDH_CSHelp_WSACommandBarNavigatorPresentationSelectionPrev  22132
#define IDH_CSHelp_WSACommandBarNavigatorPresentationSelectionNext  22133
#define IDH_CSHelp_WSACommandBarNavigatorSlideSelection             22140
#define IDH_CSHelp_WSACommandBarNavigatorSlideSelectionNumber       22141
#define IDH_CSHelp_WSACommandBarNavigatorSlideSelectionTitle        22142
#define IDH_CSHelp_WSACommandBarNavigatorSlideSelectionClear        22143
#define IDH_CSHelp_WSACommandBarNavigatorSlideSelectionList         22144
#define IDH_CSHelp_WSACommandBarLoad                                22200
#define IDH_CSHelp_WSACommandBarHide                                22300
#define IDH_CSHelp_WSACommandBarSongEdit                            22400
#define IDH_CSHelp_WSACommandBarSongEditCategory                    22410
#define IDH_CSHelp_WSACommandBarSongEditSort                        22420
#define IDH_CSHelp_WSACommandBarSongEditIndex                       22430
#define IDH_CSHelp_WSACommandBarDebug                               22500
#define IDH_CSHelp_WSACommandBarDebugSSWDisplay                     22510
#define IDH_CSHelp_WSACommandBarDebugSSWSize                        22520
#define IDH_CSHelp_WSACommandBarHelp                                22600
#define IDH_CSHelp_WSACommandBarHelpHelp                            22610
#define IDH_CSHelp_WSACommandBarHelpHelpHowTo                       22620
#define IDH_CSHelp_WSACommandBarHelpHelpCommandBar                  22630
#define IDH_CSHelp_WSACommandBarHelpHelpCopyright                   22640
#define IDH_CSHelp_WSACommandBarHelpHelpLicense                     22650
#define IDH_CSHelp_WSACommandBarHelpVisitHomepage                   22660
#define IDH_CSHelp_WSACommandBarHelpEmailAuthor                     22670
#define IDH_CSHelp_WSACommandBarHelpDebug                           22680
#define IDH_CSHelp_WSACommandBarHelpAbout                           22690
