#define IDH_Topic_WSA                                              10000
#define IDH_Topic_WSAHowTO                                         11000
#define IDH_Topic_WSAHowToEquipment                                11010
#define IDH_Topic_WSAHowToSongCreate                               11020
#define IDH_Topic_WSAHowToSongCategorize                           11030
#define IDH_Topic_WSAHowToSongSort                                 11040
#define IDH_Topic_WSAHowToSongIndex                                11050
#define IDH_Topic_WSAHowToSlideDisplay                             11060
#define IDH_Topic_WSAHowToManualPresentationDisplay                11070
#define IDH_Topic_WSAHowToTimedPresentationDisplay                 11080
#define IDH_Topic_WSACommandBar                                    12000
#define IDH_Topic_WSACommandBarNavigator                           12100
#define IDH_Topic_WSACommandBarNavigatorSlideShow                  12110
#define IDH_Topic_WSACommandBarNavigatorSlideShowLoad              12111
#define IDH_Topic_WSACommandBarNavigatorSlideShowHide              12112
#define IDH_Topic_WSACommandBarNavigatorSlideShowRun               12113
#define IDH_Topic_WSACommandBarNavigatorSlideShowPause             12114
#define IDH_Topic_WSACommandBarNavigatorSlideShowNextEffect        12115
#define IDH_Topic_WSACommandBarNavigatorSlideShowPrevEffect        12116
#define IDH_Topic_WSACommandBarNavigatorGeneral                    12120
#define IDH_Topic_WSACommandBarNavigatorGeneralExit                12121
#define IDH_Topic_WSACommandBarNavigatorGeneralHelp                12122
#define IDH_Topic_WSACommandBarNavigatorPresentationSelection      12130
#define IDH_Topic_WSACommandBarNavigatorPresentationSelectionTitle 12131
#define IDH_Topic_WSACommandBarNavigatorPresentationSelectionPrev  12132
#define IDH_Topic_WSACommandBarNavigatorPresentationSelectionNext  12133
#define IDH_Topic_WSACommandBarNavigatorSlideSelection             12140
#define IDH_Topic_WSACommandBarNavigatorSlideSelectionNumber       12141
#define IDH_Topic_WSACommandBarNavigatorSlideSelectionTitle        12142
#define IDH_Topic_WSACommandBarNavigatorSlideSelectionClear        12143
#define IDH_Topic_WSACommandBarNavigatorSlideSelectionList         12144
#define IDH_Topic_WSACommandBarLoad                                12200
#define IDH_Topic_WSACommandBarHide                                12300
#define IDH_Topic_WSACommandBarSpecial                             12400
#define IDH_Topic_WSACommandBarSpecialCategory                     12410
#define IDH_Topic_WSACommandBarSpecialSort                         12420
#define IDH_Topic_WSACommandBarSpecialIndex                        12430
#define IDH_Topic_WSACommandBarDebug                               12500
#define IDH_Topic_WSACommandBarDebugSSWDisplay                     12510
#define IDH_Topic_WSACommandBarDebugSSWSize                        12520
#define IDH_Topic_WSACommandBarHelp                                12600
#define IDH_Topic_WSACommandBarHelpHelp                            12610
#define IDH_Topic_WSACommandBarHelpHowTo                           12620
#define IDH_Topic_WSACommandBarHelpCommandBar                      12630
#define IDH_Topic_WSACommandBarHelpCopyright                       12640
#define IDH_Topic_WSACommandBarHelpLicense                         12650
#define IDH_Topic_WSACommandBarHelpVisitHomepage                   12660
#define IDH_Topic_WSACommandBarHelpEmailAuthor                     12670
#define IDH_Topic_WSACommandBarHelpDebug                           12680
#define IDH_Topic_WSACommandBarHelpAbout                           12690
#define IDH_Topic_WSACopyright                                     10100
#define IDH_Topic_WSALicense                                       10200
